apiVersion: apps/v1
kind: Deployment
metadata:
  name: assesment-app 
  labels:
    app: assesment-app
spec:
  selector:
    matchLabels:
        app: assesment-app
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: assesment-app
    spec:
      containers:
        - name: assesment-app
          image: index.docker.io/balamood/assesment:BUILD_TAG
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: assesment-app-service
  labels:
    app: assesment-app

spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: assesment-app


